server:
  host: 0.0.0.0
  port: 8000

nlp:
  server_url: "http://disabled"

store:
  type: "postgres"
  postgres:
    dsn: "postgresql://zep:zep_password@db:5432/zep?sslmode=disable"

log:
  level: "info"
